---
port: 8888
socks-port: 8889
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:6170
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5450
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  - 1.2.4.8
  fake-ip-filter:
  - "*.lan"
  - localhost.ptlogin2.qq.com
  nameserver:
  - 119.29.29.29
  - 119.28.28.28
  - 1.2.4.8
  - tls://dns.alidns.com:853
  fallback:
  - tls://dns.google:853
  - tls://dns.adguard.com:853
  - tls://1.1.1.1:853
cfw-bypass:
- localhost
- 127.*
- 10.*
- 172.16.*
- 172.17.*
- 172.18.*
- 172.19.*
- 172.20.*
- 172.21.*
- 172.22.*
- 172.23.*
- 172.24.*
- 172.25.*
- 172.26.*
- 172.27.*
- 172.28.*
- 172.29.*
- 172.30.*
- 172.31.*
- 192.168.*
- "<local>"
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false
cfw-child-process: []
Proxy:
- name: Shadowsocks
  type: socks5
  server: 127.0.0.1
  port: 1080
Proxy Group:
- name: Proxy
  type: select
  proxies:
  - Shadowsocks
Rule:
- MATCH,DIRECT
